import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ReactNode } from "react"
import { ClerkProvider } from "@clerk/nextjs"
import { auth } from "@clerk/nextjs/server"
import "./globals.css"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Contacts App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  auth()

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.variable} antialiased min-h-screen bg-white dark:bg-gray-800`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}